### ISSUE TITLE
OIDC Signing with Github now production ready?

### ISSUE THREAD

**Issue by J12934** [sigstore/cosign-installer#120]
**Question**

Hi 👋

The readme here says that OIDC signing from this action is not production ready yet.
The cosign docs page on OIDC signing states that OIDC signing is now **not** experimental anymore: https://docs.sigstore.dev/cosign/openid_signing/ 

> Identity-based signing is now fully supported in Cosign.

Does this also mean that OIDC based signing from Github Actions is production ready?

Thank you 🙌

**Comment by cpanato** [comment]
yes, we can consider production ready, several projects are using that already :)

thanks, will close this issue
