### ISSUE TITLE
Skip install if cosign is already installed

### ISSUE THREAD

**Issue by kimxogus** [sigstore/cosign-installer#140]
**Description**

We are using custom build self-hosted runner, and using cosign to sign our internal container images.
As this action runs every workflow that we build our image, it would be helpful to reduce build time and data transfer when we cache cosign binaries. but it seems current install script doesn't check preinstalled cosign binary and downloads binary everytime it runs.

**Comment by bobcallaway** [comment]
Since the action is here to explicitly install cosign, perhaps you could add a conditional around whether to invoke the action or not based on whether `cosign` is available on the local `$PATH`?
