### ISSUE TITLE
sign images using the github OIDC token without additional approval

### ISSUE THREAD

**Issue by Loki-Afro** [sigstore/cosign-installer#171]
**Question**

can one streamline the process of signing an image using the github OIDC token without manually approving the signature?

I'm referring to

```
      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build_and_push.outputs.digest }}
          TAGS: ${{ steps.docker_meta_img.outputs.tags }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}
```

from the readme.

is this somehow possible, if so: how?

**Comment by cpanato** [comment]
we use the injected token that GitHub Action add when the job started

for that you need to use the permission

```
permissions:
   id-token: write # needed for signing the images with GitHub OIDC Token
```

and in cosign it detected that the token is there and run automatically the flow without any manual interaction


Does that answer your question?

**Comment by Loki-Afro** [comment]
@cpanato cool i will try that out
