### ISSUE TITLE
README references release which doesn't exist

### ISSUE THREAD

**Issue by jpodivin** [sigstore/cosign-installer#174]
The README example suggests version 3.7.0, when the latest version is 3.6.0.

https://github.com/sigstore/cosign-installer/blob/dc72c7d5c4d10cd6bcb8cf6e3fd625a9e5e537da/README.md?plain=1#L15-L19

**Comment by cpanato** [comment]
we delayed to create the release, now it is there https://github.com/sigstore/cosign-installer/releases/tag/v3.7.0
