### ISSUE TITLE
Where and how to store encrypted private key?

### ISSUE THREAD

**Issue by dopey** [sigstore/cosign-installer#20]
**Question**

I'm using github actions and goreleaser combined with cosign - works great! My question is about the location of the encrypted private key. In the documentation the `cosign` command expects the encrypted private key to be at the root of my repo.

Should I be committing the encrypted private key to my repo? Should I be getting the private key into a file on disk before goreleaser runs in my action some other way? If so is there a prescribed way of doing this?

**Comment by cpanato** [comment]
You can add your private key as secret in the GH action and then use that.

in the snippet above that you post the flag `-key` expect the filename of the cosign key and not the content. maybe you can do the following in the steps for the action

```
cat $COSIGN_KEY_SECRET > /tmp/cosign.key
```

then in the goreleaser
```
args: ["sign-blob", "-key=/tmp/cosign.key", "-output=${signature}", "${artifact}"]
```

**Comment by dopey** [comment]
Thanks for the response @cpanato. My only concern would be accidentally `cat`ing that keyfile during an action debugging exercise in the future. But that's pretty unlikely.
