### ISSUE TITLE
enable users to speficy where they want to install cosign 

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign-installer#36]
**Description**

By default cosign will be installed into the directory `$HOME/.cosign`, maybe we can accept a variable from users to let them specify where they want to install cosign binary.

WDYT @dentrax @cpanato?

**Comment by developer-guy** [comment]
would you mind assigning this to me 🙋🏻‍♂️

**Comment by cpanato** [comment]
sounds good to me
