### ISSUE TITLE
Support Windows and Mac installation

### ISSUE THREAD

**Issue by JamieMagee** [sigstore/cosign-installer#42]
**Description**

Currently this action defaults to installing the `linux-amd64` version of `cosign`, however GitHub Actions also provides Windows and Mac runners[^1]. The runner also works on ARM32 and ARM64 self-hosted runners[^2]. Windows, Mac, and ARM versions of `cosign` are already published[^3].

[^1]: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
[^2]: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#architectures
[^3]: https://github.com/sigstore/cosign/releases/latest

**Comment by cpanato** [comment]
i will work on the windows support

thanks Bob for the linux/mac

**Comment by bobcallaway** [comment]
#49 adds windows support
