### ISSUE TITLE
provide an option or specific version name to download cosign via go install command

### ISSUE THREAD

**Issue by developer-guy** [sigstore/cosign-installer#45]
**Description**

in [setup-ko](https://github.com/imjasonh/setup-ko) project there is a special version name called `tip` which allows us to install ko via go install from main. It'd be helpful to people who might want to work with the latest changes of the `cosign` before waiting for its newer version.

**Comment by developer-guy** [comment]
please feel free to assign this to me if you liked the idea, my friend, @cpanato 😋

**Comment by cpanato** [comment]
go for it!! 🎉
