### ISSUE TITLE
Action as verified in the github marketplace

### ISSUE THREAD

**Issue by JeNeComprendPas** [sigstore/cosign-installer#67]
**Description**

Hi, is it possible to verify the action in the marketplace, according to [this issue](https://github.com/bitnami-labs/sealed-secrets/issues/762) from sealed-secrets project ?
There is a [link](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges#for-github-actions) to have more information about marketplace verification.

It's seems sigstore is already verified by github.

Thank you in advance

**Comment by cpanato** [comment]
thanks! I will check how are can make this happen

**Comment by JeNeComprendPas** [comment]
Thanks!

**Comment by cpanato** [comment]
this is now complete :)
<img width="301" alt="Screenshot 2022-05-17 at 23 49 56" src="https://user-images.githubusercontent.com/4115580/168916291-15f4c940-2e6f-4ee2-9baf-b241c5d484f7.png">
