### ISSUE TITLE
Consider versioning this action

### ISSUE THREAD

**Issue by saschagrunert** [sigstore/cosign-installer#81]
Hey folks, what do you think about versioning this installer in the same way other GitHub actions do, like having a `v1` branch rather than pointing to `main`?

**Comment by cpanato** [comment]
That sounds like a nice idea. the `v1` tag is a moving tag, right? was checking the others and did not find a branch but instead just a tag

**Comment by saschagrunert** [comment]
@cpanato I guess both will work, but you're right the sample workflow outlines a moving tag: https://github.com/actions/toolkit/blob/main/docs/action-versioning.md

**Comment by cpanato** [comment]
done: https://github.com/sigstore/cosign-installer/releases/tag/v1
